os:
  - linux
language: python
python:
  - "3.6"
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
services:
  - mysql
env:
  -DJANGO=2.1 DB=mysql
install:
  - pip install -r REQUIREMENTS.txt
before_script:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.23.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - mysql -e 'create database evoting;' -u root
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py loaddata templateMigrationData.json
  - python manage.py runserver &
script:
  - python manage.py test tests/
  - kill %1